---
name: replication_ppr
channels:
  - conda-forge
  - nodefaults

dependencies:
  - conda-lock
  - ipykernel
  - jupyterlab
  - pandas
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - python=3.11
  - pyyaml
  - setuptools_scm
  - statsmodels
  - toml
  - requests
  - beautifulsoup4
  - selenium
  - numpy
  - r-base
  - r-fixest
  - r-data.table
  - r-plm
  - r-modelsummary
  - r-jsonlite
  - r-AER
  - r-quantreg
  - r-kableExtra
  - pip:
      - -e .
      - kaleido
      - country_converter
      - geopy
